FROM alpine:latest

LABEL maintainer="miladimos" version="0.5.0"

RUN apk add --no-cache \
            ca-certificates \
            curl \
            tar  \ 
            xz \
            openssl \
            git \
            nodejs \
            nodejs-npm 

EXPOSE 8000

