version: 3.9

services:

  backend:
    depends_on:
      - database
    build: ./backend
    ports:
      - 8000:8000
    enviroment:
      DB_NAME: ''

  frontend:
    build:  ./frontend
    ports:
      - 80:8001

  database:
    image: jj
    ports:
      - 2313:21313
    volumes:
      - user:/data/db
    
  cache:
    image: redis

volumes:
